web:
  build: .
  working_dir: /home/app
  ports:
    - "3000:3000"
    - "5858:5858"
  command: npm start
  volumes:
    - .:/home/app
  environment:
    NODE_ENV: development
  links:
    - mongo
    - redis
mongo:
  image: mongo:latest
  command: mongod --smallfiles --quiet --logpath=/dev/null
  ports:
   - "27017:27017"
redis:
  image: redis:latest
  ports:
   - "6379:6379"
